FROM debian
LABEL maintainer 'aluno cod3r <Lucas Furio Franco at cod3r.com.br>'

#define um argumento para o build, sendo que caso não seja passado, o valor default será file
ARG S3_BUCKET=files

#atribui o valor recebido pelo argumento dessa forma
ENV S3_BUCKET=${S3_BUCKET}
